[options]
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$gRBi7L23lvJe632PEcJYyw$0NN9aMxC9AMsSVBGiXhJqnhekKpBgroXWMiIrZCCAQ/YIk4ki0NBJ16T7wPOl4MSyijg1UlgWrInd9xS4jupiA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
proxy_mode = True

